### ISSUE TITLE
Ability to autohide wingpanel

### ISSUE THREAD

**Issue by codesforacookie** [elementary/switchboard-plug-pantheon-shell#100]
This is a feature in macOS, allowing the option to hide the top panel when not in use. Is this a good idea for elementary OS? Because I think it would do more good than harm.

**Comment by danrabbit** [comment]
Gonna close this for this repo since it can't be solved here. This feature request has already been reported for the correct repo here: https://github.com/elementary/wingpanel/issues/53

Closing this report as "Out of scope" for switchboard-plug-pantheon-shell
