### ISSUE TITLE
Set as Desktop Background for djvu

### ISSUE THREAD

**Issue by Djaler** [elementary/switchboard-plug-pantheon-shell#131]
There are an option to set .djvu file as desktop background in context menu. I don't think that this is good idea to set book as a background

**Comment by peteruithoven** [comment]
It's probably possible to further specify the MimeType:
https://github.com/elementary/switchboard-plug-pantheon-shell/blob/master/set-wallpaper-contract/set-wallpaper.contract.in#L5
More information: https://github.com/elementary/contractor#writing-contract-files
