### ISSUE TITLE
some shortcuts doesn't work

### ISSUE THREAD

**Issue by YousefSaber** [elementary/switchboard-plug-pantheon-shell#138]
running elementary OS 0.4.1 Loki

some shortcuts doesn't work like save an area to clipboard and there are some missing shortcuts like minimizing all applications and turning off the screen please check again on all keyboard screenshots and make sure it works well

**Comment by ryonakano** [comment]
Hello, thank you for your reporting.

> some shortcuts doesn't work like save an area to clipboard

This is already reported at https://github.com/elementary/screenshot/issues/34

> there are some missing shortcuts like minimizing all applications

This is at https://github.com/elementary/switchboard-plug-keyboard/issues/162

> turning off the screen

I think you can do this if you're using laptop.

**Comment by YousefSaber** [comment]
@ryonakano I'm using a PC so good that you are aware of this issue

**Comment by YousefSaber** [comment]
@ryonakano this issue has been solved in elementary OS 5.0 Juno

**Comment by Blast-City** [comment]
> @ryonakano this issue has been solved in elementary OS 5.0 Juno

Hi.

Sorry for late reply.

Does Juno have the "minimize all windows" shortcut?

**Comment by ryonakano** [comment]
@Blast-City I think no, since elementary is trying to part with minimizing windows.

**Comment by Blast-City** [comment]
> @Blast-City I think no, since elementary is trying to part with minimizing windows.

Thanks.
