### ISSUE TITLE
Configure docklets in the dock page

### ISSUE THREAD

**Issue by donadigo** [elementary/switchboard-plug-pantheon-shell#139]
Right now, we have a separate "Multitasking view" in the applications menu, while that works, I think that it would make more sense to have this item as a configurable switch in the dock pane. There could also be more specific items added like "Switch to a new workspace" switch.

**Comment by danirabbit** [comment]
I'm going to close this since we're planning to rewrite the dock and I don't think there's any plans to support docklets
