### ISSUE TITLE
why elementary OS can't run applications extracted from tar.xz files

### ISSUE THREAD

**Issue by YousefSaber** [elementary/switchboard-plug-pantheon-shell#140]
Package managers suffers from slow updates and new versions of apps arrive slowly on package managers ( firefox hasn't been updated to version 62.0.2 on package manager yet ) 

so some developers compress their applications into tar.xz so this way the application can receive better updates quickly ( firefox , telegram and Visual Studio Code do the same thing ) 

why elementary OS can't run these extracted applications 

![image](https://user-images.githubusercontent.com/33742499/45915429-dc753800-be54-11e8-8b01-c6bf271ac886.png)
![image](https://user-images.githubusercontent.com/33742499/45915435-f0b93500-be54-11e8-8c7c-491b535c833c.png)
![image](https://user-images.githubusercontent.com/33742499/45915440-fc0c6080-be54-11e8-9f2b-9302984415bd.png)

**Comment by BaptisteGelez** [comment]
This file may miss the "executable" permission. You can check by right-clicking on it, going to "Properties" and then "Permissions".

**Comment by BaptisteGelez** [comment]
I think it is an issue with the app itself, not elementaryOS. An icon would be displayed if a .desktop file was installed (but it looks like none is provided… you can create it by yourself with [AppEditor](https://appcenter.elementary.io/com.github.donadigo.appeditor/) if you want).

**Comment by YousefSaber** [comment]
@BaptisteGelez thanks very much AppEditor solved the problem completely
