### ISSUE TITLE
no minimize

### ISSUE THREAD

**Issue by neknawall** [elementary/switchboard-plug-pantheon-shell#142]
![screenshot from 2018-09-24 09 51 38](https://user-images.githubusercontent.com/31073707/45940067-81bc1780-bfdf-11e8-8927-50a61b5519f3.jpeg)

**Comment by ryonakano** [comment]
Duplication of #125

**Comment by neknawall** [comment]
bullshit bullshit bullshit

**Comment by cassidyjames** [comment]
Closing as dupe
