### ISSUE TITLE
missing features 

### ISSUE THREAD

**Issue by YousefSaber** [elementary/switchboard-plug-pantheon-shell#144]
the OS lacks a shortcut to turn off the display , minimize all applications and insert emojis which is a common features among OS nowadays

**Comment by cassidyjames** [comment]
Please do not file compound issues, as it's difficult to track. Instead, file individual issues for individual requests.

Super + L locks the session, which then turns off the display in a few seconds. I don't see much value in just turning the display off?

elementary OS is moving away from the concept of minimize. But if the point is to see your desktop, you can just hit Super + End to go to a new workspace.

Inserting emoji works in any native GTK3 text entry with Ctrl + ;
