### ISSUE TITLE
Can't enumerate SYSTEM_BACKGROUNDS_PATH

### ISSUE THREAD

**Issue by worldofpeace** [elementary/switchboard-plug-pantheon-shell#151]
##### Platform
[NixOS](https://nixos.org/)

##### Issue
switchboard-plug-pantheon-shell can't enumerate  `SYSTEM_BACKGROUNDS_PATH` when set to `/run/current-system/sw/share/backgrounds`.

This directory will be populated with a symlink to a path in the nix store (specifically the elementary wallpapers) which are and always will be read only.

##### Errors
It prints this warning in the output
```
WARNING **: 13:52:26.290:  Wallpaper.vala:397: Operation not supported
```

##### Exact Directory Structure
```
/run/current-system/sw/share/backgrounds
❯ l                                                                                                                            
Permissions Size User Group Date Modified Name
dr-xr-xr-x     - root root  31 Dec  1969  .
dr-xr-xr-x     - root root  31 Dec  1969  ..
lrwxrwxrwx   105 root root  31 Dec  1969  elementary -> /nix/store/ji2g3yrx69dfws57bk5qq4ai699ckd84-elementary-wallpapers-2018-10-05/share/backgrounds/elementary

/run/current-system/sw/share/backgrounds/elementary
❯ l                                                                                                                  
Permissions Size User Group Date Modified Name
dr-xr-xr-x     - root root  31 Dec  1969  .
dr-xr-xr-x     - root root  31 Dec  1969  ..
.r--r--r--  1.3M root root  31 Dec  1969  Ashim DSilva.jpg
.r--r--r--  3.0M root root  31 Dec  1969  Carmine De Fazio.jpg
.r--r--r--  369k root root  31 Dec  1969  Jonas Nilsson Lee.jpg
.r--r--r--  7.7M root root  31 Dec  1969  leigh-kendell-581.jpg
.r--r--r--  8.8M root root  31 Dec  1969  Luca Bravo.jpg
.r--r--r--  2.5M root root  31 Dec  1969  Morskie Oko.jpg
.r--r--r--  3.6M root root  31 Dec  1969  Mr. Lee.jpg
.r--r--r--  2.3M root root  31 Dec  1969  Pablo Garcia Saldana.jpg
.r--r--r--  927k root root  31 Dec  1969  Photo by SpaceX.jpg
.r--r--r--  2.1M root root  31 Dec  1969  Rob Bye.jpg
.r--r--r--  2.5M root root  31 Dec  1969  Ryan Schroeder.jpg
.r--r--r--  1.5M root root  31 Dec  1969  Sunset by the Pier.jpg

```

**Comment by davidmhewitt** [comment]
I suspect this was probably a duplicate of #157, or that was a duplicate of this depending on how you want to look at it :wink: 

Could you re-test from master when you get chance and close this issue if it is resolved?

**Comment by worldofpeace** [comment]
> I suspect this was probably a duplicate of #157, or that was a duplicate of this depending on how you want to look at it wink

All polarities held in equality :smile:

> Could you re-test from master when you get chance and close this issue if it is resolved?

Everything works as expected again. Thanks for fixing this :sparkles:
