### ISSUE TITLE
inconsistent usage of pantheon / shell / desktop

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-pantheon-shell#152]
- the project is named `switchboard-plug-pantheon-shell`
- the meson project is named `pantheon-desktop`
- the appstream ID is `io.elementary.switchboard.pantheon-shell` (which doesn't match what's in the appcenter blacklist, see https://github.com/elementary/default-settings/issues/98)
- translations are named `pantheon-desktop-plug`

**Comment by danirabbit** [comment]
@decathorpe I think this is resolved now? Everything should be io.elementary.settings.desktop

**Comment by decathorpe** [comment]
Except https://github.com/elementary/switchboard-plug-pantheon-shell, I think, yes :)

**Comment by danirabbit** [comment]
Right yeah, the repo names themselves I want to change soon but also trying to minimize disruption 😅

**Comment by decathorpe** [comment]
I understand. Though GitHub would provide redirects for the old name, IIRC.

Closing this issue since it looks like it's all fixed other than the repo name. Thank you for following up!
