### ISSUE TITLE
Non-FHD images are stretched in the desktop images overview

### ISSUE THREAD

**Issue by wout** [elementary/switchboard-plug-pantheon-shell#153]
Although, a minor issue, it's still not really pleasant on the eyes, as stretched images tend to be:

![desktops-aspect-ratio-issue](https://user-images.githubusercontent.com/107324/47527794-bf90b200-d8a3-11e8-9451-de3522557e02.png)

A fit to frame, while maintaining the aspect ratio of the image, would be better.

**Comment by cassidyjames** [comment]
I think for this, crop and zoom would be fine since that's what the desktop does by default, too.

**Comment by danirabbit** [comment]
Fixed in #386
