### ISSUE TITLE
Problem With Main Settings

### ISSUE THREAD

**Issue by Loway-MT** [elementary/switchboard-plug-pantheon-shell#197]
When I Press The ShutDown Or Restart Buttons
Nothing Happens

**Comment by danrabbit** [comment]
OP can you clarify a little bit? Are you referring to physical buttons on your computer or buttons in the shutdown dialog or some other interface?

**Comment by cassidyjames** [comment]
Unless I hear otherwise, I presume this is a duplicate of https://github.com/elementary/wingpanel-indicator-session/issues/97
