### ISSUE TITLE
positive feedback

### ISSUE THREAD

**Issue by sudorandomguy** [elementary/switchboard-plug-pantheon-shell#203]
hello,

Elementary OS works amazingly!
it would be nice to have a darkmode or an option to switch to a dark theme.

another thing about the email app.
adding Gmail doesn't work, selecting Gmail from the menu doenst work.
selecting other and filling in the right imap and smtp with ports, doenst work.

**Comment by lenemter** [comment]
Thanks for your feedback :smiley:
