### ISSUE TITLE
After I lock desktop there is no way to wake it again.

### ISSUE THREAD

**Issue by internetman420** [elementary/switchboard-plug-pantheon-shell#219]
Please forgive me, and move the subject, if this is in the wrong place.

Problem:
I lock my session. After it is locked there is no mouse movement or keyboard tapping in the world that makes the screen turn on and show me the login prompt again.

Setup: 
ElementaryOS 5.1.3 Hera
5+ years old MacMini

Obv this makes EOS quite shitty for me atm, since i care about security :(

Please advice me on how to provide logfiles etc. to try and troubleshoot where the problem lies. 

Last note; I have prior connected a second display to this system, but the problem persists with the second one being plugged in or not. I also THINK that the problem existed before I connected a second display, but I am not 100% certain.

Thanks in advance! :)

**Comment by Yofiel** [comment]
I suffer from the same problem and this also happens if I suspend the system.

**Comment by tgederberg** [comment]
I have the same/similar issue on a Dell Inspiron with an i5-3337U processor and Intel Graphics Controller.  I have an external monitor connected via a HDMI cable and my power settings set as in the attachment.  However, after the computer suspends, the only way I can resume is to open the lid on the laptop.
![Screenshot from 2020-04-30 20 48 04](https://user-images.githubusercontent.com/46580805/80866157-e6773380-8c52-11ea-9f04-e16704899a4c.png)

**Comment by hanaral** [comment]
This git page is for the settings panel for desktop personalisation. You should probably be posting this [here](https://github.com/elementary/gala/issues), but I think this is a display driver issue and not a DE issue

**Comment by internetman420** [comment]
Any tips on how one could try to troubleshoot if it is a DE issue or not?
