### ISSUE TITLE
Add dark mode as an option in settings

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/switchboard-plug-pantheon-shell#223]
As the title suggests, a toggle for dark mode (even an auto switcher is welcomed if possible) in settings without having to download third party (elementary tweaks) would be a great addition to EOS. Browsing white pages at night is blinding even on the lowest brightness. 
Thank you

**Comment by danrabbit** [comment]
This was added in #216 and will ship in elementary OS 6 :)
