### ISSUE TITLE
Operating system locked up when dock behavior drop down was open and password prompt opened

### ISSUE THREAD

**Issue by rigglemania** [elementary/switchboard-plug-pantheon-shell#232]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
After recently installing the operating system, I was on the dock settings page and clicked the drop down to control when it is hidden ("Hide when"). While the drop down was still open, the OS launched the password prompt, wanting me to enter my password to configure the firewall. When this happened, the entire OS locked up. Everything was frozen and no keys worked to regain focus and close. The only solution was to hard power off the machine.

### To Reproduce
The steps are not easily reproducible and I am guessing the issue is probably a race condition between the two actions. But here's the best I can do.

1. Go to the dock settings page and open up the drop down to control when the dock is hidden
2. Wait for something in the background to trigger the prompt to enter your password
3. System locks up and none of the keys on the keyboard work anymore

### Expected behavior
The operation system doesn't crash

## Platform Information
![Hardware Info](https://user-images.githubusercontent.com/1371650/85211446-4c10a380-b317-11ea-8e62-3dcb253c60db.png)

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by hanaral** [comment]
I'm not able to reproduce this on elementary 6 daily, so I assume it was caused by the older version of the display server elementary OS Hera has. Do you know what caused the firewall popup? I don't recall ever getting one

**Comment by rigglemania** [comment]
I do not remember what caused the firewall popup. Maybe it was something with auto updates in the background, but that's just speculation. If I ever encounter this again, I'll try to pay attention to the reason why the password prompt was initiated.
