### ISSUE TITLE
Provide a setting to enable systemwide use of OpenDyslexic.

### ISSUE THREAD

**Issue by KeironO** [elementary/switchboard-plug-pantheon-shell#234]
Having a toggle to enable the use of [opendyslexic](https://www.opendyslexic.org/) as a feature would be brilliant from a usability POV.

I could have a go at implementing it in the same way that elementary-tweaks does, wherein fonts are rest to system defaults upon untoggling.

**Comment by cassidyjames** [comment]
@KeironO I'd also love to hear your thoughts on what to label this setting. I imagine a switch below the text size settings makes sense. Would something like this sound accurate:

>**Dyslexia-friendly text: `(o--)`**
>Bottom-heavy shapes and increased character spacing can help improve legibility and reading speed.

I want to make sure it's precise while including enough information for someone to judge whether or not they would want to use it.

**Comment by KeironO** [comment]
Dyslexia-friendly text sounds perfect.

Given how busy you are, are you willing to do this?

**Comment by cassidyjames** [comment]
@KeironO if you wanted to give it a shot, it would be great. Otherwise, someone on the team can take a look when they get a chance.

**Comment by KeironO** [comment]
@cassidyjames Sure thing.

**Comment by cassidyjames** [comment]
@KeironO Thanks again for your work on this!
