### ISSUE TITLE
"Desktop" option in settings crashes on click after latests updates.

### ISSUE THREAD

**Issue by AJ552** [elementary/switchboard-plug-pantheon-shell#243]
"Desktop" option in Switchboard, _after latests updates_, is working no more.
Everytime I click on it crashes the entire switchboard application.
This is a **critical bug**.

Error's output: `(io.elementary.switchboard:18429): GLib-GIO-ERROR **: 04:50:03.159: Settings schema 'io.elementary.settings-daemon.prefers-color-scheme' is not installed`

1) Open System Settings
2) Click on option "Desktop"

**Comment by ryonakano** [comment]
I believe this issue is due to [the failing build](https://code.launchpad.net/~elementary-os/+recipe/settings-daemon-daily) of settings daemon.

**Comment by ryonakano** [comment]
I thought I fixed this issue by adding dependencies (elementary/settings-daemon#12) but I was missing a comma to separate them. This might be why the latest building still fails. I've just sent a new PR to add missing comma.

**Comment by cassidyjames** [comment]
@AJ552 to clarify, you're on an elementary OS 6 pre-release build?

**Comment by ryonakano** [comment]
If you're on daily it should be fixed in the latest update

**Comment by cassidyjames** [comment]
Gonna close this as it was resolved in daily builds. If more information is provided that it wasn't a daily build, then we can re-open and investigate this further.
