### ISSUE TITLE
Dock: "Hide when" empty when the switch is disabled

### ISSUE THREAD

**Issue by Blast-City** [elementary/switchboard-plug-pantheon-shell#256]
## What Happened

When the dock hide mode switch is disabled the drop down menu doesn't show any option. Enabling the switch doesn't select any of the dropdown options keeping the hiding mode disabled.

## Expected Behavior

The "Hide when" dropdown menu should remember the option that was selected when the hide switch was disabled and select that option whe the switch is enabled.

## Steps to Reproduce

1. Open the Desktop settings and select the Dock settings.
2. Disable the Hide switch.
3. Close the settings window. 
4. Open the Desktop settings again and select the Dock settings.

## Platform Information

elementary OS 5.1.7 Hera

**Comment by mcclurgm** [comment]
I found the cause of the issue, but I'm not sure how to design a fix. We set the value of the combobox only when the "none" hide setting isn't selected: see https://github.com/elementary/switchboard-plug-pantheon-shell/blob/e2b3a0ab18b7e4de6bc90c94ecab4261ea31ff77/src/Views/Dock.vala#L83-L90

To fix this, we'd first need to add some way of setting the combobox in the else case. Then we'd also need to either somehow store the last used hide option (excluding none) to populate the combobox with, or we could add another option to the combobox for none. (Although in the second case, that would duplicate the switch behavior, so I don't think that makes sense.)
