### ISSUE TITLE
Enable hot corners to "Show desktop"

### ISSUE THREAD

**Issue by internetman420** [elementary/switchboard-plug-pantheon-shell#260]
Sometimes when I listen to music or just want to hide the awful news on the web I like to just hide all the apps and only show the desktop.

It would ble splendid if this was one of the actions the hot corners could have, I know you can execute a command for it but my mother can't do that :D

**Comment by danrabbit** [comment]
In elementary OS, we don't use minimize. The equivalent action would be to switch to a new workspace, which is already available as an option.

Closing as "design conflict"

**Comment by internetman420** [comment]
I agree :-) Thanks for the optional idea.
