### ISSUE TITLE
Selected wallpaper marker doesn't match accent color (eOS 6 Public Beta).

### ISSUE THREAD

**Issue by lilvadim** [elementary/switchboard-plug-pantheon-shell#274]
Accent color is purple:
![Screenshot from 2021-05-13 01-28-10](https://user-images.githubusercontent.com/32203382/118026479-07588580-b38b-11eb-9eba-8e435af739d5.png)
But selection marker is blueish:
![Screenshot from 2021-05-13 01-28-21](https://user-images.githubusercontent.com/32203382/118026455-01fb3b00-b38b-11eb-8940-5fbe287ffcb5.png)

**Comment by cassidyjames** [comment]
Yeah the same thing happens in Files, because we're using a full-color icon here instead of a symbolic with the color drawn in CSS. Is this something we want to address, @danrabbit?

**Comment by danrabbit** [comment]
We should probably look into using a checkbox here since it would probably be easier to do with an overlay than dealing with iconview and cell renderers
