### ISSUE TITLE
Screenshot reference in README is broken

### ISSUE THREAD

**Issue by ibnesayeed** [elementary/switchboard-plug-pantheon-shell#283]
## What Happened

#282 removed the `data/screenshot.png` file and replaced it with a more specific name, which resulted in breaking the reference in the README file.

## Expected Behavior

The README should show/reference one of the four screenshots in the `data` folder.

## Steps to Reproduce

Load https://github.com/elementary/switchboard-plug-pantheon-shell in a web browser

### Logs

None

## Platform Information

GitHub

**Comment by cassidyjames** [comment]
Thanks! Fixed in fb5bec6fe7f90eb0348f9875f8ddd43e40cd9d43

**Comment by ibnesayeed** [comment]
Looks like you have a mug full of coffee on your desk @cassidyjames. While I was drafting a PR, it was fixed already. :wink:
