### ISSUE TITLE
Replace pressure reveal with delay

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-pantheon-shell#287]
## Problem

Pressure reveal doesn't work reliably in OS 6 for some reason, breaking on HiDPI, multiple displays, and in other seemingly random ways.

## Proposal

We could replace the off-by-default pressure reveal feature with a way to change the reveal delay. We could potentially even keep the name “pressure reveal” if all it did was switch between something like 150ms and 300ms, as the end result will feel very similar.

If we're thinking about replacing Plank long term, this might be a simpler route than trying to fix the issues with true pressure reveal in the current codebase.

## Prior Art

We upped the reveal delay in OS 6 to reduce accidental popups, but with nonfunctional pressure reveal, it might not be enough.

**Comment by danirabbit** [comment]
Closing since in the new dock pressure is handled in the window manager
