### ISSUE TITLE
Add minimize in the 'When the cursor enters the corner of the display."

### ISSUE THREAD

**Issue by TryingHardNovice** [elementary/switchboard-plug-pantheon-shell#303]
### Problem

There is a maximize option but there is no minimize option.

### Proposal

Add 'Minimize' to the list which includes 'Do nothing', 'Multitasking view', ...

**Comment by tintou** [comment]
We do not support minimize anymore: https://github.com/elementary/switchboard-plug-pantheon-shell/issues/97
