### ISSUE TITLE
Desktop icon missing in System Settings

### ISSUE THREAD

**Issue by FunkySalamander** [elementary/switchboard-plug-pantheon-shell#367]
### What Happened?

I did a revert to defaults in System & now I can't change my wallpaper because the Desktop icon is missing from the System Settings window.
![2023-08-25_System_Settings](https://github.com/elementary/switchboard-plug-pantheon-shell/assets/125952784/1b1c1c1d-58c0-4b7d-bf06-e58621c3f229)

### Steps to Reproduce

Reset System Settings > System > Restore Default Settings to default
Right Click to Change Wallpaper
System Settings opens with Desktop icon missing

### Expected Behavior

Reset System Settings > System > Restore Default Settings to default
Right Click to Change Wallpaper
System Settings opens to Desktop section to change wallpaper

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
It probably got deleted somehow. Try to reinstall it by executing this command in Terminal:

```
sudo apt reinstall switchboard-plug-pantheon-shell
```

**Comment by FunkySalamander** [comment]
> It probably got deleted somehow. Try to reinstall it by executing this command in Terminal:
> 
> ```
> sudo apt reinstall switchboard-plug-pantheon-shell
> ```

That did it, thanks!
