### ISSUE TITLE
[Linux Mint/Pantheon] Wallpaper previews in settings do not appear

### ISSUE THREAD

**Issue by akirapink** [elementary/switchboard-plug-pantheon-shell#383]
### What Happened?

after installing Pantheon on Linux Mint, i can't change the wallpaper
also, the previews of the available wallpapers don't work. not even blank squares, but instead nothing at all
![image](https://github.com/elementary/wallpapers/assets/33667869/287250dd-a4a0-46b8-a1bd-a8190bd87e8f)

### Steps to Reproduce

- install Pantheon on Linux Mint (unsupported by default, add ppa first)
- go to System Settings, then Desktop
- wallpaper previews will not function, won't be able to change wallpaper from default either

### Expected Behavior

- will be able to change wallpaper from defualt

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
On elementary, wallpapers are taken from `jpg` files found in `file:///usr/share/backgrounds/` and `file:///home/<username>/.local/share/backgrounds`.  The thumbnails shown are either found in `/home/<username>/.cache/thumbnails/` or are generated on the fly using the "/org/freedesktop/thumbnails/Thumbnailer1" Dbus interface.

If you have these then try running `G_MESSAGES_DEBUG=all` io.elementary.switchboard` in a terminal and see if there are any warning messages.

**Comment by akirapink** [comment]
UPD: problem went away on its own
