### ISSUE TITLE
Automatic dark mode not working

### ISSUE THREAD

**Issue by tony-alk** [elementary/switchboard-plug-pantheon-shell#427]
### What Happened?

The dark mode does not toggle automatically when set to sunset to sunrise setting

### Steps to Reproduce

1. System settings
2. desktop 
3. dark mode sunset to sunrise setting 

### Expected Behavior

The mode is supposed to switch automatically based on the sunset timing in the current location

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by teamcons** [comment]
Duplicate of https://github.com/elementary/settings-daemon/issues/162

Could you add to the thumbs up on 162 please ?

**Comment by danirabbit** [comment]
Closing as a duplicate of the linked issue :)
