### ISSUE TITLE
Hang + high CPU when selecting "Pictures" wallpaper source

### ISSUE THREAD

**Issue by JPLeBreton** [elementary/switchboard-plug-pantheon-shell#67]
When I open the Desktop settings panel and change the wallpaper source from "Background" to "Pictures", the app hangs for a long time (>60 seconds) and CPU usage on one core stays at nearly 100%. I then see what appears to be thumbnails for every image in every subdirectory of my /home, including tons of images in dev dirs (eg bitmaps from autogenerated documentation O_O) that no user would reasonably want to use. This happens every time I open the panel and change source to Pictures.
Desired behavior would be something like:
- No hang, thumbnails begin displaying immediately top-to-bottom and if there are a large number of them then use a generic proxy thumbnail until the real thumbnail can be loaded.
- Cache these thumbnails so each one only has to be generated the first time it appears.
- Only search in the user's ~/Pictures, don't crawl their entire /home for all valid images or whatever it seems to be doing.

**Comment by danirabbit** [comment]
This issue report seems related to a previous design that we no longer use. Instead of choosing a wallpaper directory, we now have an option to import photos into the local wallpapers folder. So this is no longer reproducible
