### ISSUE TITLE
Thumbnails size 

### ISSUE THREAD

**Issue by Djaler** [elementary/switchboard-plug-pantheon-shell#78]
Thumbnails are too small since the last commit
![2017-09-13 09 24 43](https://user-images.githubusercontent.com/7964583/30362609-76f6137a-9865-11e7-9035-f12f533e3212.png)

**Comment by davidmhewitt** [comment]
The size reduction was intentional, as explained in #75. I guess the spacing in the FlowBox looks a little odd, it looks like it should be able to fit one more wallpaper on that top line. I'll see if there's anything that can be done about this later.
