### ISSUE TITLE
Display artist data in a tooltip for wallpapers

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-pantheon-shell#81]
There's sometimes an Artist field in the exif data. We should display that when possible in a tooltip like how MATE shows this

![ubuntu-mate-background](https://user-images.githubusercontent.com/7277719/30924411-a4a2b8f6-a37c-11e7-8ea7-082502c5b954.png)

**Comment by davidmhewitt** [comment]
So, the way MATE handles this is with an XML file they ship with the backgrounds. Worth considering something similar?

https://github.com/mate-desktop/mate-backgrounds/blob/master/desktop/mate-desktop.xml.in.in

**Comment by danrabbit** [comment]
Naw, I think that’d be harder to maintain than getting the data from the image itself. It could pretty easily fall out of sync with the image and the feature would only work for included images
