### ISSUE TITLE
Auto change Wallpaper

### ISSUE THREAD

**Issue by torikulhabib** [elementary/switchboard-plug-pantheon-shell#94]
how about with Auto change Wallpaper picture

**Comment by cassidyjames** [comment]
This would need some design input to figure out how it works. I'm not sure that it's something we want in the core, though; there are third-party apps that can cycle the wallpaper.

**Comment by SixFingeredAmish** [comment]
@cassidyjames I agree that there are apps that already do this, but I think this should be a built-in feature.

As for how it’d work, users when selecting their wallpaper would get an option to cycle photos from a folder, every ___ minutes/hours/days.

**Comment by peteruithoven** [comment]
I'm afraid this is a duplicate of https://github.com/elementary/switchboard-plug-pantheon-shell/issues/22
