### ISSUE TITLE
Remove "Minimize current window" hotcorner

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-pantheon-shell#97]
We've moved away from Minimize almost everywhere else, but are still carrying this hotcorner.

**Comment by msiqueira553** [comment]
Why remove minimize hotcorner? I use it a lot!

**Comment by NaungYeOo** [comment]
> We've moved away from Minimize almost everywhere else, but are still carrying this hotcorner.

This is why I can't find minimize current window in hot corner.
Why did you guys remove minimize? Am I missing something?

**Comment by tintou** [comment]
@NaungYeOo Explained in this article from 2011 https://web.archive.org/web/20160614115819/https://old.elementary.io/journal/whats-window-controls
